server:
  port: 8080

## 连接池配置
spring:
  mvc:
    ##服务器访问图片虚拟路径 真实访问路径  http://localhost:8080/pic/图片名字
    static-path-pattern: /pic/**

  web:
    resources:
      ##本地存放图片的位置
      static-locations: file:D://imgs

  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动
    #连接路径
    url: jdbc:mysql://192.168.100.100:3306/shoppe_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Liu.201912
    #连接池配置
    druid:
      initialSize: 5 # 初始化连接数
      minIdle: 5 # 最小空闲连接数
      maxActive: 20 # 最大连接数
      maxWait: 60000 # 最大等待时间
      timeBetweenEvictionRunsMillis: 60000 # 连接空闲多久进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 # 连接在池中


##mybatis-plus的日志文件配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.edu.shopapi.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    web: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

